-- AlterTable
ALTER TABLE "Stock" ADD COLUMN     "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "user" TEXT;

-- AlterTable
ALTER TABLE "StockMaster" ADD COLUMN     "timestamp" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "user" TEXT;
